CALL crearUsuario('usuario1', 'password123', 'Usuario Uno', 'a');
CALL crearUsuario('usuario2', 'password123', 'Usuario Dos', 'a');
CALL crearUsuario('usuario3', 'password123', 'Usuario Tres', 'a');
CALL crearUsuario('usuario4', 'password123', 'Usuario Cuatro', 'a');
CALL crearUsuario('usuario5', 'password123', 'Usuario Cinco', 'a');
CALL crearUsuario('usuario6', 'password123', 'Usuario Seis', 'a');
CALL crearUsuario('usuario7', 'password123', 'Usuario Siete', 'a');
CALL crearUsuario('usuario8', 'password123', 'Usuario Ocho', 'a');
CALL crearUsuario('usuario9', 'password123', 'Usuario Nueve', 'a');
CALL crearUsuario('usuario10', 'password123', 'Usuario Diez', 'a');
CALL crearUsuario('usuario11', 'password123', 'Usuario Once', 'a');
CALL crearUsuario('usuario12', 'password123', 'Usuario Doce', 'a');
CALL crearUsuario('usuario13', 'password123', 'Usuario Trece', 'a');
CALL crearUsuario('usuario14', 'password123', 'Usuario Catorce', 'a');
CALL crearUsuario('usuario15', 'password123', 'Usuario Quince', 'a');
CALL crearUsuario('usuario16', 'password123', 'Usuario Dieciseis', 'a');
CALL crearUsuario('usuario17', 'password123', 'Usuario Diecisiete', 'a');
CALL crearUsuario('usuario18', 'password123', 'Usuario Dieciocho', 'a');
CALL crearUsuario('usuario19', 'password123', 'Usuario Diecinueve', 'a');
CALL crearUsuario('usuario20', 'password123', 'Usuario Veinte', 'a');
CALL nuevoAmigo('usuario1', 'usuario15');
CALL nuevoAmigo('usuario1', 'usuario2');
CALL nuevoAmigo('usuario1', 'usuario3');
CALL nuevoAmigo('usuario1', 'usuario20');
CALL nuevoAmigo('usuario4', 'usuario3');
CALL nuevoAmigo('usuario4', 'usuario2');
CALL nuevoAmigo('usuario4', 'usuario18');
CALL nuevoAmigo('usuario16', 'usuario11');
CALL nuevoAmigo('usuario16', 'usuario20');
CALL nuevoAmigo('usuario16', 'usuario14');
CALL nuevoAmigo('usuario16', 'usuario4');
CALL nuevoAmigo('usuario16', 'usuario5');
CALL nuevoAmigo('usuario16', 'usuario19');
CALL nuevoAmigo('usuario16', 'usuario13');
CALL nuevoAmigo('usuario20', 'usuario3');
CALL nuevoAmigo('usuario20', 'usuario4');
CALL nuevoAmigo('usuario20', 'usuario9');
CALL nuevoAmigo('usuario20', 'usuario10');
CALL nuevoAmigo('usuario20', 'usuario15');
CALL nuevoAmigo('usuario20', 'usuario19');
CALL nuevoAmigo('usuario17', 'usuario1');
CALL nuevoAmigo('usuario17', 'usuario8');
CALL nuevoAmigo('usuario17', 'usuario9');
CALL nuevoAmigo('usuario17', 'usuario15');
CALL nuevoAmigo('usuario17', 'usuario20');